name: Generate Folder Structure

on:
  push:
    branches:
      - '**'

jobs:
  generate-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate folder structure JSON
        run: |
          python3 <<EOF
          import os, json

          def get_structure(root):
              structure = {}
              for dirpath, dirnames, filenames in os.walk(root):
                  # Ignore hidden folders like .git
                  if '/.' in dirpath or dirpath.startswith('.'):
                      continue
                  rel_path = os.path.relpath(dirpath, root)
                  if rel_path == ".":
                      rel_path = "/"
                  structure[rel_path] = filenames
              return structure

          structure = get_structure(".")
          with open("data.json", "w") as f:
              json.dump(structure, f, indent=2)
          EOF

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update data.json with folder structure"
            git push
          fi
